// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
<<<<<<< HEAD
=======
/// <reference types="node" />
>>>>>>> 1e4d4176030e715c5c4b6f94a227eee803e1eef3
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
